### ISSUE TITLE
duplicate Accession ID in the json file: de41a735

### ISSUE THREAD

**Issue by babarlelephant** [vector-engineering/covidcg#274]
Hi, thank you for your great work, I'm using it [there](http://babarlelephant.free-hoster.net/cov2/)

Just to say there is a duplicate Accession ID in the json file: de41a735

**Comment by atc3** [comment]
Hi,

Thanks for bringing this to our attention. The Accession ID hashes are generated from a numerical sequence, so I don't think this is a hash collision... hopefully it's not a duplicated sequence somewhere.

I'll investigate further and let you know what I find.

Thanks,
Albert

**Comment by atc3** [comment]
Closing as the new version of the site is no longer sending individual sequence data to the front-end, and thus the Accession ID hashing has been removed.
