### ISSUE TITLE
Per-service installation: location of defs.json is hardcoded so flask server fails

### ISSUE THREAD

**Issue by monkollek** [vector-engineering/covidcg#381]
I would change this so it's not hardcoded and perhaps location be specific in the CONFIGFILE?
https://github.com/vector-engineering/covidcg/blob/master/services/server/cg_server/constants.py#L13

I''m assuming it should point to this file on the repo?
https://github.com/vector-engineering/covidcg/blob/master/src/constants/defs.json

**Comment by atc3** [comment]
Yes, thanks for the feedback. The current path is relative to the container during a docker deployment, but maybe it would be better to define this path via. an environment variable that defaults to the relative path in the repository

**Comment by atc3** [comment]
Closed by #384, please let me know if this fixed your problem
