### ISSUE TITLE
Per-service installation: example bash script to launch flask server should have export commands

### ISSUE THREAD

**Issue by monkollek** [vector-engineering/covidcg#382]
When you run this script it fails. When you point export command it works.
https://github.com/vector-engineering/covidcg/blob/master/services/server/serve.sh#L2-L4

Also there should be mention of specify CONFIGFILE somewhere with the test on launching flask server as the default is hardcoded in
https://github.com/vector-engineering/covidcg/blob/master/services/server/cg_server/config.py#L21

**Comment by atc3** [comment]
Thanks for the feedback, this should be fixed by #384. Let me know if you are still having issues with the per-service deployment of the flask server
