### ISSUE TITLE
RSVG Interface

### ISSUE THREAD

**Issue by favelava** [vector-engineering/covidcg#431]
Write React component that allows user to select between RSVA and RSVB reference sequences

**Comment by favelava** [comment]
Frontend issues being worked on. Instead of implementing a bunch of switch statements, see if there's a way to dynamically import a .js file depending on the config.virus field

**Comment by favelava** [comment]
initial values for the stores are now being imported from a .js file in the constants folder. The naming convention for these folders is initalValues.{config.virus}.js. These files are parsed and stored in an intialValuesStore when the App is created and then read by configStore and plotSettingsStore

**Comment by atc3** [comment]
Closing - already done as part of larger RSV issue
