### ISSUE TITLE
RSVCG Alpha

### ISSUE THREAD

**Issue by favelava** [vector-engineering/covidcg#478]
- [x] Fix Default Values for RSVCG
- [x] Ask slack channel for opinions on RSV name
- [x] Finalize RSVCG Name
- [ ] Create RSVCG Logo
- [ ] Rewrite RSVCG About Tab
<br>

- [x] Fix RSVCG Download Sequences
- [x] In Surveillance Plot, download option is downloading covid data. Fix that
- [x] Change rsvgs01/02 to 3' and 5' UTR
- [x] Add domains from uniprot
- [x] Remove primer option from Select Sequences
- [x] Can't type in Match Sequence
- [x] Change Match Sequence default
- [x] Fix tooltips around the site
- [x] Change reference below entropy plot to A or B instead of WIV04
- [x] Remove covid-specific warnings
- [x] In Surveillance Plot, replace "Spike" references with "Fusion"
<br>
If AZ sends the reference sequences they use for genotypes:

- [x] Ask RSV AZ people ONLY for genotype seqs (Keep VE, Dave, Bahar on chain)
- [x] Update reference.json for RSV
- [x] Add genotype alignment to workflow
- [x] Base subtype assignment off of genotype alignment
- [x] Add genotype to full dataframe
<br>

- [ ] Add Examples for RSV

<br>

- [x] Create database for RSV site
- [x] Fix npm dependencies
- [x] Deploy container to Google Cloud Run with versioning (following covidcg's process)
- [x] Push local data to google cloud db
- [x] Set up Cloud Run service
- [x] Set up DNS via Google Domains
- [x] Link DNS to Cloud Run
- [x] Push RSVCG alpha site

**Comment by favelava** [comment]
Examples for RSV:
Compare A and B worldwide
Compare A and B in US
Compare mutations in A in Europe/Asia/whatever is interesting

**Comment by atc3** [comment]
Closed by #527, #536
