### ISSUE TITLE
RSV: default only shows subtype A

### ISSUE THREAD

**Issue by chan-solo** [vector-engineering/covidcg#542]
users have to use filter seq interface to also select B

**Comment by chan-solo** [comment]
is there a way to set it so that this default only applies to when the Compare Mutations tab is grouping sequences by Mutations; when grouping by Subtypes, it should automatically switch to cover both A and B sequences.

**Comment by chan-solo** [comment]
This is still a problem in the Compare Mutations tab

**Comment by chan-solo** [comment]
Even when a user picks B as a reference genome, the right most margin filter still picks subtype A as default
<img width="1253" alt="Screen Shot 2022-06-25 at 7 50 48 PM" src="https://user-images.githubusercontent.com/40721645/175793876-8f8c4ae9-da05-4c09-9f78-742f4c767780.png">

**Comment by atc3** [comment]
Thanks for pointing this out -- I fixed for the top bar but did not account for the filtering modal.

**Comment by atc3** [comment]
Closing - fixed in latest version
