### ISSUE TITLE
RSV: strange mutation names in left margin on Compare mutations tab

### ISSUE THREAD

**Issue by chan-solo** [vector-engineering/covidcg#548]
When reference genome is set to the fusion gene, there are jumbled mutation names in the left margin

**Comment by atc3** [comment]
I've seen this before but can't reliably reproduce this error. The next time it shows up, can you screenshot and send me the filtering parameters so I can reproduce it?

**Comment by atc3** [comment]
Closed by #568, by adding some common-sense filters on indel lengths
