### ISSUE TITLE
Global sequencing effort svg download bug

### ISSUE THREAD

**Issue by chan-solo** [vector-engineering/covidcg#560]
<img width="610" alt="Screen Shot 2022-07-01 at 6 55 35 PM" src="https://user-images.githubusercontent.com/40721645/176975856-5310f921-7903-4e24-afc8-70805ba08fa4.png">

**Comment by atc3** [comment]
The SVG export function is a part of the Vega library and it's out of our control to define which texts to hide and which not to. Not sure how to fix this without editing the Vega source code and adding a separate attribute to the text mark to tell the SVG exporter whether or not to render it.
