### ISSUE TITLE
Lineage Report not showing for NT and Gene__AA

### ISSUE THREAD

**Issue by luigibrancati** [vector-engineering/covidcg#595]
I've been trying to visit the Lineage Reports page in order to download the reports, but only the Protein_AA page is showing. When selecting either NT or Gene_AA from the dropdown menu, a blank page appears

![image](https://user-images.githubusercontent.com/41120885/210457281-3daa1ddb-64fc-401b-adf5-8e347e6e2902.png)

When selecting NT, I can see the data is fetched correctly, but the console shows the following errors

![image](https://user-images.githubusercontent.com/41120885/210457750-beb053f4-fbfb-49da-8976-c4351ffbb77a.png)

The pics above are from Firefox 108.0.1, but the same happens with Chrome and Edge.

**Comment by atc3** [comment]
Hi,

Sorry for the trouble. I just pushed a fix for the site (v2.7.1), does that fix your issue?

**Comment by luigibrancati** [comment]
Hi,

The issue has been fixed, thanks!

Il mer 4 gen 2023, 06:37 Albert Tian Chen ***@***.***> ha
scritto:
