### ISSUE TITLE
Phylotree plot

### ISSUE THREAD

**Issue by atc3** [vector-engineering/covidcg#83]
Phylogenetic tree of lineages (backbone), and also make the line thickness represent the number of sequences in it. Should adapt to the locations selected

**Comment by babarlelephant** [comment]
Hello, art poon/covizu is maintaining a tree of pangolin lineages https://filogeneti.ca/CoVizu/data/timetree.2020-12-11T18:33:42.nwk 

With the result of Select Sequences you can compute the number of sequences falling in each branch and draw the result with https://www.cssscript.com/phylogenetic-tree-figtree/

**Comment by atc3** [comment]
Closed by #337
